apiVersion: apps/v1
kind: Deployment
#informacion del deployment
metadata:
  name: wordpress-deployment
  labels:
    component: wordpress
#spec -> estado deseado, se compara el status y se lo trata de llevar a lo
#especificado en el spec
spec:
  #crea 2 pods
  replicas: 2
  #matchea con otros objetos que tengan ese label
  selector:
    matchLabels:
      component: wordpress
  strategy:
      type: RollingUpdate
      rollingUpdate:
           maxSurge: 2
           maxUnavailable: 0
  template:
    metadata:
      labels:
        component: wordpress
    spec:
      containers:
        - image: wordpress:4.8-apache
          name: wordpress
          env:
          - name: WORDPRESS_DB_HOST
            value: mysql-cluster-ip-service
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
          ports:
          - containerPort: 8080
            name: wordpress
